export const NAVIGATION_LINKS = {
    HOME: '/',
    PRIVACY_POLICY: '/privacy-policy',
    TERMS_CONDITIONS: '/terms-conditions',
    CUSTOMER_FEEDBACK: '/customer-feedback',
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    PAYMENTS: '/payments',
    CHECKOUT_RETURN: '/payments/checkout-return',
    USER_DASHBOARD: '/dashboard',
    PET_PROFILES: '/dashboard/pet-profiles',
    DIARY_ENTRIES: '/dashboard/diary-entries',
    MY_DIARY: '/dashboard/my-diary',
    MAGIC_STUDIO: '/dashboard/magic-studio',
    TIMELINE_VIEW: '/dashboard/timeline-view',
    SETTINGS: '/dashboard/settings',

    ADMIN_LOGIN: '/auth/admin/login',
    ADMIN_DASHBOARD: '/admin/dashboard',
    MANAGE_USERS: '/admin/dashboard/users',
    MANAGE_USER_SUBSCRIPTIONS: '/admin/dashboard/user-subscriptions',
};
